### ISSUE TITLE
Forces doubt

### ISSUE THREAD

**Issue by RodrigoMA93** [erwincoumans/motion_imitation#60]
You did a wonderful job in your repository of locomotion_controller_example. I was analizing your code and I had the doubt that if the contact forces of torque_stance_leg_controller are calculated with the archive mpc_osqp.cc.

I send you my greetings and I hope that you can answer my question.
![Selección_022](https://user-images.githubusercontent.com/64650728/116632455-e02a9e80-a91c-11eb-98b3-0c43fba898aa.png)

**Comment by erwincoumans** [comment]
Yes, the ground reaction forces are computed using the qp solver. The robot should walk fine using those forces.
