### ISSUE TITLE
using GPU

### ISSUE THREAD

**Issue by code-wd** [erwincoumans/motion_imitation#61]
hi, thank you for sharing you code, and I wonder to know whether this code can run with GPU. I build env for tensorflow GPU, but I find it cannot use GPU.
thank you

**Comment by suiup** [comment]
Hi, I meet the same problem. I tried many times but I could not use the tensorflow-gpu.
Looking forward to your reply.
Thank you

**Comment by erwincoumans** [comment]
For this repo, I think we used CPU to train.
