### ISSUE TITLE
Question on the friction setting for randomization

### ISSUE THREAD

**Issue by pengzhi1998** [erwincoumans/motion_imitation#62]
Hi, thank you for your great work!

However, I have a question about a setting for randomization. In the paper, you mentioned the training range for the lateral friction is [0.05, 1.25] which is a relatively big range. However, in the [code](https://github.com/google-research/motion_imitation/blob/master/motion_imitation/envs/utilities/minitaur_env_randomizer_config.py) it seems to be [0.5, 1.25]. 

Which one did you choose in the paper's experiments during training and what's the reason? Is that because friction is a very crucial impact factor?

Thank you!

**Comment by erwincoumans** [comment]
I think we used [0.5,1.25] for the paper, it maybe a typo.
