### ISSUE TITLE
python versions

### ISSUE THREAD

**Issue by nicolas42** [erwincoumans/motion_imitation#64]
I have difficulties using this system with python 3.9 so I set up a conda environment with python 3.7.  It took me a while to work this out.  Could you put a small note in the readme about the python version that you use?

Btw great repo

**Comment by erwincoumans** [comment]
We tried with python 3.7 and python 3.8. Thanks for the report, added a mention.
~~~
Getting Started
We use this repository with Python 3.7 or Python 3.8 on Ubuntu, MacOS and Windows.
~~~
