### ISSUE TITLE
Additional motor torques

### ISSUE THREAD

**Issue by RodrigoMA93** [erwincoumans/motion_imitation#65]
Is not an issue, just for a better understanding, how do you calculate the additional motor torques that are used in the Hybrid Control of your robot. Do you do a substraction of the desired motor torques minus the actual motor torques?
![Selección_034](https://user-images.githubusercontent.com/64650728/123153321-26871000-d42b-11eb-9e5d-9b589fd72d43.png)

**Comment by erwincoumans** [comment]
The additional torques are computed using convex MPC, for the stance feet. In other words: the swing feet use position control (PD) while stance feet using torque control through those 'additional_torques).
