### ISSUE TITLE
position drifting happens when set v=0 in whole_body_controller_example.py

### ISSUE THREAD

**Issue by zhuyijie88** [erwincoumans/motion_imitation#66]
In this function,
```python
_generate_example_linear_angular_speed(t)
```
I set the linear and angular  velocity both zero. When  simulated robot A1 marks time for tens of seconds, it drifts from the origin position  gradually. I want to  know the reason of this phenomenon, is it attributed to unprecise dynamic modeling? How do we fix it?

**Comment by erwincoumans** [comment]
The mpc model (inertia, center of mass location) is not very accurate, probably causing some drift. Also, convex mpc ignores feet mass, but there is some mass. There maybe other reasons for drift (feet collision, bit of sliding perhaps).

One workaround (hack) could be to measure drift compensate through the velocity.
