### ISSUE TITLE
A1 or Laikago, to which model do parameters belong

### ISSUE THREAD

**Issue by peschn** [erwincoumans/motion_imitation#67]
First of all thanks a lot for releasing the fantastic code, it makes life much easier! Just a small question though:

In [motion_imitation/robots/a1.py](https://github.com/google-research/motion_imitation/blob/master/motion_imitation/robots/a1.py) the class is named A1 but all comments refer to Laikago. So my question is, are the parameters that are specified in this file for the Unitree Laikago or the Unitree A1 robot?

Thanks a lot.

**Comment by erwincoumans** [comment]
Ah, A1 was a quick copy/paste from Laikago, we need to modify the names.

**Comment by erwincoumans** [comment]
Thanks for the report, fixed https://github.com/google-research/motion_imitation/commit/4286b50a2e8a107ab39361f29f6aa42733d79a37
